# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algorithm.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61lgorithm.proto\x12\talgorithm\"9\n\x0bInputCTData\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05\x64type\x18\x03 \x01(\t\":\n\x0cOutputUSData\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05\x64type\x18\x03 \x01(\t2P\n\x10\x41lgotirhmService\x12<\n\x07\x45xecute\x12\x16.algorithm.InputCTData\x1a\x17.algorithm.OutputUSData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'algorithm_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUTCTDATA']._serialized_start=30
  _globals['_INPUTCTDATA']._serialized_end=87
  _globals['_OUTPUTUSDATA']._serialized_start=89
  _globals['_OUTPUTUSDATA']._serialized_end=147
  _globals['_ALGOTIRHMSERVICE']._serialized_start=149
  _globals['_ALGOTIRHMSERVICE']._serialized_end=229
# @@protoc_insertion_point(module_scope)
